theme: null

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

website: https://kvarak.github.io
baseurl: ""
basewebsite: /dnd
permalink: date

# Repository information for GitHub Pages and sitemap generation
repository: kvarak/dnd
url: https://dnd.rigo.nu

include:
  - search.json
  - robots.txt

plugins:
  - jekyll-sitemap

collections_dir: docs

collections:
  Campaigns:
    output: true
  Classes:
    output: true
  Classes2:
    output: true
  Equipment:
    output: true
  Folk:
    output: true
  FolkGeneric:
    output: true
  Resources:
    output: true
  Rules:
    output: true
  RulesCharacter:
    output: true
  RulesCombat:
    output: true
  RulesEquipment:
    output: true
  RulesExtra:
    output: true
  RulesMagic:
    output: true
  Specific:
    output: true
  _OldRules:
    output: true
